{{- define "raven.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "raven.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name (include "raven.name" .) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{/* Stable Service name so Postfix / delivery.yaml resolve raven's socketmap. */}}
{{- define "raven.serviceName" -}}
{{- (((.Values.global).serviceNames).raven) | default "raven" }}
{{- end }}

{{- define "raven.selectorLabels" -}}
app.kubernetes.io/name: {{ include "raven.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "raven.labels" -}}
{{ include "raven.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/* Primary domain + derived mail hostname (single source: global.domain). */}}
{{- define "raven.domain" -}}
{{- required "global.domain is required (e.g. --set global.domain=example.com)" ((.Values.global).domain) }}
{{- end }}

{{- define "raven.mailHostname" -}}
{{- (.Values.global).mailHostname | default (printf "mail.%s" (include "raven.domain" .)) }}
{{- end }}

{{/* S3 endpoint (defaults to the in-cluster seaweedfs Service). */}}
{{- define "raven.s3Endpoint" -}}
{{- if .Values.blobStorage.endpoint }}
{{- .Values.blobStorage.endpoint }}
{{- else }}
{{- printf "http://%s:8333" ((((.Values.global).serviceNames).s3) | default "seaweedfs-s3") }}
{{- end }}
{{- end }}

{{- define "raven.s3AccessKey" -}}
{{- (((.Values.global).s3).accessKey) | default .Values.blobStorage.accessKey }}
{{- end }}

{{/*
S3 secretKey.

This used to recompute the seaweedfs subchart's derivation
(`printf "%s-silver-seaweedfs-s3" .Release.Name | sha256sum | trunc 40`) so both
charts agreed on a fresh one-command install without a cross-lookup — which made
the key of every default install computable offline by anyone. seaweedfs now
generates it once and raven READS it, so nothing here derives anything.

Raven is configured by file (raven.yaml / delivery.yaml), not by environment, so
a secretKeyRef cannot reach it directly. The config Secret therefore carries the
placeholder below, deployment.yaml injects the real key from the seaweedfs Secret
as an env var, and an init container substitutes it into a private copy of the
config at pod start. Two things fall out of that:
  - the S3 key no longer sits in raven's config Secret at all; it exists only in
    the seaweedfs Secret;
  - a fresh one-command install works, because the reference is resolved by the
    kubelet at pod start, after Helm has applied the seaweedfs Secret.

An explicitly configured key (global.s3.secretKey / blobStorage.secretKey) is
still written inline, so raven can run standalone against an external S3 with no
seaweedfs Secret present. Without one, and with the seaweedfs subchart disabled,
the pod stops at CreateContainerConfigError on the missing Secret — set
global.s3.secretKey (or global.s3.secretName) in that case.
*/}}
{{- define "raven.s3SecretKeyPlaceholder" -}}
__SILVER_S3_SECRET_KEY__
{{- end }}

{{- define "raven.s3SecretKeyExplicit" -}}
{{- (((.Values.global).s3).secretKey) | default .Values.blobStorage.secretKey }}
{{- end }}

{{- define "raven.s3SecretKey" -}}
{{- include "raven.s3SecretKeyExplicit" . | default (include "raven.s3SecretKeyPlaceholder" .) }}
{{- end }}

{{/*
Secret holding the S3 credential generated by the seaweedfs subchart, and the key
within it. The name is NOT importable across subcharts (raven cannot see
seaweedfs's .Values), so the seaweedfs naming rule is reproduced here — the same
reason raven.tlsSecretName duplicates the umbrella's rule below. These MUST agree:
  charts/silver/charts/seaweedfs/templates/_helpers.tpl (seaweedfs.secretName)
  here
Override global.s3.secretName if the seaweedfs subchart is renamed via
nameOverride/fullnameOverride, or to point raven at an external S3 credential.
*/}}
{{- define "raven.s3SecretName" -}}
{{- (((.Values.global).s3).secretName) | default (printf "%s-seaweedfs-s3" .Release.Name | trunc 63 | trimSuffix "-") }}
{{- end }}

{{- define "raven.s3SecretKeyRefKey" -}}
{{- (((.Values.global).s3).secretKeyRefKey) | default "secretKey" }}
{{- end }}

{{/*
Thunder hosts. Both default to the BARE domain, not mail.<domain>: Thunder serves
the <domain> certificate on :8090 and publishes its OAuth issuer as
https://<domain>:8090, so mail.<domain> is not a SAN and TLS verification fails.

Both are the public name rather than the in-cluster Service name because raven
speaks HTTPS with no skip-verify or custom-CA option, and silver-thunder-service
is not on the cert either. In-cluster calls therefore hairpin via the node's
external IP (see finding #7).
*/}}
{{- define "raven.thunderHost" -}}
{{- .Values.thunder.host | default (include "raven.domain" .) }}
{{- end }}

{{- define "raven.thunderPublicHost" -}}
{{- .Values.thunder.publicHost | default (include "raven.domain" .) }}
{{- end }}

{{/*
cert-manager TLS Secret for IMAPS. Mirrors the umbrella's silver.tlsSecretName
(charts/silver/templates/_helpers.tpl) rather than calling it, so this subchart
still renders standalone — the same reason raven.domain/raven.mailHostname are
duplicated above.

The dots->dashes naming rule exists in three places and they MUST agree:
  charts/silver/templates/_helpers.tpl   (silver.tlsSecretName)
  charts/silver/templates/certificate.yaml (the Certificate's secretName)
  here
*/}}
{{- define "raven.tlsSecretName" -}}
{{- ((.Values.global).tlsSecretName) | default (printf "%s-tls" (include "raven.mailHostname" . | replace "." "-")) }}
{{- end }}

{{/* Secret holding the rendered raven.yaml + delivery.yaml (contain S3 key). */}}
{{- define "raven.configSecretName" -}}
{{- printf "%s-config" (include "raven.fullname" .) }}
{{- end }}

{{/*
Secret mounted at /certs. Precedence:
  tls.existingSecret -> global.tlsSecretName -> mail-<domain-dashed>-tls -> self-signed
The cert-manager name is preferred over the generated self-signed Secret so a
one-command install with global.domain set picks up the real cert automatically.
Falls back to self-signed only when there is no global.domain at all (standalone).
*/}}
{{- define "raven.certSecretName" -}}
{{- if .Values.tls.existingSecret }}
{{- .Values.tls.existingSecret }}
{{- else if and (((.Values.global).tls).enabled) ((.Values.global).domain) }}
{{- include "raven.tlsSecretName" . }}
{{- else }}
{{- printf "%s-certs" (include "raven.fullname" .) }}
{{- end }}
{{- end }}
